[project]
name = "vntd"
version = "1.1.0"
description = "Unofficial client for Vinted API"
readme = "README.md"
license = "MIT"
authors = [
    { name = "louis.mltp", email = "107575190+MINLEGO@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "curl-cffi>=0.15.0",
    "fake-useragent>=2.2.0",
]

keywords = ["vntd", "vinted", "wrapper", "api"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/MINLEGO/vntd"
Repository = "https://github.com/MINLEGO/vntd"
Changelog = "https://github.com/MINLEGO/vntd/blob/main/CHANGELOG.md"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.15",
]
